# Generated by Django 4.1.3 on 2022-12-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedlesson',
            name='day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='friday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='friday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='monday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='monday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='saturday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='saturday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='sunday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='sunday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='thursday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='thursday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='tuesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='tuesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='wednesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='wednesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_gap_weeks',
            field=models.PositiveIntegerField(choices=[(1, 'Biweekly'), (2, 'Weekly'), (4, 'Fortnightly'), (8, 'Monthly')], default=2),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
