# Generated by Django 4.1.3 on 2022-12-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='lesson_gap_weeks',
            field=models.PositiveIntegerField(choices=[(1, 'Biweekly'), (2, 'Weekly'), (4, 'Fortnightly'), (8, 'Monthly')], default=2),
        ),
    ]
