# Generated by Django 4.1.3 on 2022-11-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='days_available',
            field=models.CharField(default='1234567', max_length=7),
        ),
    ]
