# Generated by Django 4.1.3 on 2022-11-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[(1, 'Student'), (2, 'Teacher')], default=1, max_length=1),
        ),
    ]
