# Generated by Django 4.1.3 on 2022-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='payment_history',
            field=models.TextField(blank=True),
        ),
    ]
