# Generated by Django 4.1.3 on 2022-11-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='lesson_gap',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='num_lessons',
            field=models.PositiveIntegerField(),
        ),
    ]
