# Generated by Django 4.1.3 on 2022-12-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_bookedlesson_day_lessonrequest_friday_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedlesson',
            name='day',
        ),
    ]
