# Generated by Django 4.1.3 on 2022-11-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_student_new_password_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='new_password',
        ),
    ]
