# Generated by Django 4.1.3 on 2022-12-07 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonrequest_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
