# Generated by Django 4.1.3 on 2022-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_rename_payment_history_lessonrequest_payment_history_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='payment_history_csv',
        ),
        migrations.AddField(
            model_name='user',
            name='payment_history_csv',
            field=models.TextField(blank=True),
        ),
    ]
